import {
  Component,
  OnInit,
  OnDestroy,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import QRCode from 'qrcode';
import { IndexerService, IndexedProject } from '../../services/indexer.service';
import { BitcoinUtilsService } from '../../services/bitcoin.service';
import { NetworkService } from '../../services/network.service';
import { ThemeService } from '../../services/theme.service';

type ProjectTypeName = 'invest' | 'fund' | 'subscription';
type PaymentNetwork = 'lightning' | 'onchain' | 'liquid' | 'import';
type PaymentStatus = 'awaiting' | 'received';

interface PaymentStage {
  number: number;
  percentage: number;
  releaseDate: string;
  amount: string;
  amountSats?: number;
}

const MIN_AMOUNT_BTC = 0.001;
const APP_THRESHOLD_SATS = 1_000_000; // 0.01 BTC
const HUB_INVESTMENTS_KEY = 'angor-investments-hub';

@Component({
  selector: 'app-invest',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './invest.component.html',
  styleUrls: ['./invest.component.css'],
})
export class InvestComponent implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private indexer = inject(IndexerService);
  private bitcoin = inject(BitcoinUtilsService);
  private networkService = inject(NetworkService);
  protected themeService = inject(ThemeService);

  projectId = '';
  project = signal<IndexedProject | null>(null);
  loading = signal<boolean>(true);
  error = signal<string | null>(null);

  isDark = computed(() => this.themeService.isDarkTheme());

  // ---- Form state ----
  investmentAmount = signal<string>('');
  amountError = signal<string>('');
  selectedQuickAmount = signal<number | null>(null);
  selectedSubscriptionPattern = signal<'pattern1' | 'pattern2' | null>(null);
  selectedFrequency = signal<'weekly' | 'monthly'>('monthly');
  selectedInstallments = signal<'3' | '6'>('3');

  // Validation errors (shown on submit attempt)
  subscriptionPatternError = signal<string>('');
  frequencyError = signal<string>('');
  installmentsError = signal<string>('');
  amountValidationError = signal<string>('');

  // ---- Modal state ----
  showAppDownloadModal = signal<boolean>(false);
  showInvestModal = signal<boolean>(false);
  showImportWalletModal = signal<boolean>(false);
  showWalletBackupModal = signal<boolean>(false);
  showBackupPasswordModal = signal<boolean>(false);
  showSuccessModal = signal<boolean>(false);
  paymentStatus = signal<PaymentStatus>('awaiting');
  seedDownloaded = signal<boolean>(false);
  backupPassword = signal<string>('');

  // Payment network selection
  networkTabs: { id: PaymentNetwork; label: string; caption: string }[] = [
    { id: 'lightning', label: 'Lightning', caption: 'Instant via LN' },
    { id: 'onchain', label: 'On-Chain', caption: 'Bitcoin mainnet' },
    { id: 'liquid', label: 'Liquid', caption: 'Liquid network' },
    { id: 'import', label: 'Import', caption: 'Seed phrase' },
  ];
  selectedNetwork = signal<PaymentNetwork>('lightning');
  private previousNetwork: PaymentNetwork = 'lightning';

  // Seed import
  seedPhraseInput = signal<string>('');
  seedError = signal<string>('');
  seedSuccess = signal<boolean>(false);

  // Mock payment endpoints (front-end only; would be generated by backend)
  private investmentAddress = 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh';
  private lightningInvoice = 'lnbc1pvjluezsp5un3qexampleinvoice0s28uz';
  private liquidAddress = 'ex1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq';

  quickAmounts = [0.001, 0.01, 0.1, 0.5];
  qrDataUrl = signal<string>('');

  private paymentTimeout: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    // Regenerate QR when network / theme / modal changes
    effect(() => {
      const open = this.showInvestModal();
      const network = this.selectedNetwork();
      const dark = this.isDark();
      if (open && network !== 'import') {
        this.generateQr(this.currentNetworkAddress(), dark);
      }
    });
  }

  async ngOnInit(): Promise<void> {
    window.scrollTo(0, 0);
    this.projectId = this.route.snapshot.paramMap.get('id') ?? '';
    if (!this.projectId) {
      this.error.set('Project not found');
      this.loading.set(false);
      return;
    }

    try {
      const project = await this.indexer.fetchProject(this.projectId);
      if (!project) {
        this.error.set('Project not found');
        this.loading.set(false);
        return;
      }
      this.project.set(project);

      // Load stats for the nav bar (total raised / progress)
      try {
        const stats = await this.indexer.fetchProjectStats(this.projectId);
        if (stats) {
          const current = this.project();
          if (current) {
            this.project.set({ ...current, stats });
          }
        }
      } catch {
        // Stats are non-critical for the invest form
      }

      // Initialize subscription pattern default (matches prototype)
      if (this.projectTypeName() === 'subscription' && !this.selectedSubscriptionPattern()) {
        this.selectedSubscriptionPattern.set('pattern1');
        this.investmentAmount.set(this.satsToBTC(this.calculateSubscriptionPrice('pattern1')));
      }
    } catch (err) {
      console.error('Failed to load project:', err);
      this.error.set('Failed to load project');
    } finally {
      this.loading.set(false);
    }
  }

  ngOnDestroy(): void {
    if (this.paymentTimeout) {
      clearTimeout(this.paymentTimeout);
    }
  }

  // ---- Derived project data ----

  projectTypeName(): ProjectTypeName {
    const type = this.project()?.details?.projectType ?? 0;
    if (type === 1) return 'fund';
    if (type === 2) return 'subscription';
    return 'invest';
  }

  projectTitle(): string {
    const p = this.project();
    return p?.metadata?.name || p?.projectIdentifier || 'Project';
  }

  targetBtc(): string {
    return this.bitcoin.toBTC(this.project()?.details?.targetAmount ?? 0, 8);
  }

  raisedBtc(): string {
    return this.bitcoin.toBTC(this.project()?.stats?.amountInvested ?? 0, 8);
  }

  progressPercent(): number {
    const invested = this.project()?.stats?.amountInvested ?? 0;
    const target = this.project()?.details?.targetAmount ?? 0;
    if (!target || target <= 0) return 0;
    return Number(((invested / target) * 100).toFixed(1));
  }

  subscriptionPriceSats(): number {
    // Subscription price is not part of the on-chain model yet; default matches prototype
    return 20000;
  }

  actionButtonText = computed(() => {
    const type = this.project()?.details?.projectType ?? 0;
    if (type === 2) return 'Subscribe';
    if (type === 1) return 'Fund';
    return 'Invest Now';
  });

  // ---- Fees / totals ----

  networkFee = '0.00000391';
  angorFeePercentage = 1;

  angorFee = computed(() => {
    const amount = parseFloat(this.investmentAmount()) || 0;
    return (amount * (this.angorFeePercentage / 100)).toFixed(4);
  });

  totalAmount = computed(() => {
    const amount = parseFloat(this.investmentAmount()) || 0;
    const minerFee = parseFloat(this.networkFee) || 0;
    const platformFee = parseFloat(this.angorFee()) || 0;
    return (amount + minerFee + platformFee).toFixed(4);
  });

  // ---- Schedule ----

  paymentStages = computed<PaymentStage[]>(() => {
    const amount = parseFloat(this.investmentAmount()) || 0;
    const type = this.projectTypeNameFromSignal();

    if (type === 'subscription' && this.selectedSubscriptionPattern()) {
      const patternCount = this.selectedSubscriptionPattern() === 'pattern1' ? 3 : 6;
      const priceSats = this.subscriptionPriceSats();
      const today = new Date();
      const stages: PaymentStage[] = [];
      for (let i = 0; i < patternCount; i++) {
        const paymentDate = new Date(today.getFullYear(), today.getMonth() + i + 1, 1);
        stages.push({
          number: i + 1,
          percentage: Math.floor(100 / patternCount),
          releaseDate: paymentDate.toISOString().split('T')[0],
          amount: this.satsToBTC(priceSats),
          amountSats: priceSats,
        });
      }
      return stages;
    }

    if (type === 'fund' && this.selectedFrequency() && this.selectedInstallments() && amount > 0) {
      const installments = parseInt(this.selectedInstallments(), 10) || 3;
      const perInstallment = amount / installments;
      const remainder = amount % installments;
      const isWeekly = this.selectedFrequency() === 'weekly';
      const today = new Date();
      const stages: PaymentStage[] = [];
      for (let i = 0; i < installments; i++) {
        let paymentDate: Date;
        if (isWeekly) {
          paymentDate = new Date(today);
          paymentDate.setDate(today.getDate() + i * 7 + 7);
        } else {
          paymentDate = new Date(today.getFullYear(), today.getMonth() + i + 1, 1);
        }
        const paymentAmount =
          i === 0 ? (perInstallment + remainder).toFixed(4) : perInstallment.toFixed(4);
        stages.push({
          number: i + 1,
          percentage: Math.round((parseFloat(paymentAmount) / amount) * 100),
          releaseDate: paymentDate.toISOString().split('T')[0],
          amount: paymentAmount,
        });
      }
      return stages;
    }

    // Invest projects: use real stages from project details
    const projectStages = this.project()?.details?.stages ?? [];
    return projectStages.map((stage, index) => ({
      number: index + 1,
      percentage: stage.amountToRelease,
      releaseDate: new Date(stage.releaseDate * 1000).toISOString().split('T')[0],
      amount: (amount * (stage.amountToRelease / 100)).toFixed(4),
    }));
  });

  private projectTypeNameFromSignal(): ProjectTypeName {
    const type = this.project()?.details?.projectType ?? 0;
    if (type === 1) return 'fund';
    if (type === 2) return 'subscription';
    return 'invest';
  }

  paymentPricePerInstallment = computed(() => {
    const type = this.projectTypeNameFromSignal();
    if ((type === 'subscription' || type === 'fund') && this.investmentAmount()) {
      const amount = parseFloat(this.investmentAmount()) || 0;
      const count = this.paymentStages().length;
      if (count > 0) return (amount / count).toFixed(4);
    }
    return '0.0000';
  });

  // ---- Validation ----

  canSubmit = computed(() => {
    if (!this.project()) return false;
    const type = this.projectTypeNameFromSignal();
    const amount = parseFloat(this.investmentAmount());
    if (type === 'subscription') {
      return this.selectedSubscriptionPattern() !== null && !!this.investmentAmount() && amount > 0 && !this.amountError();
    }
    if (type === 'fund') {
      return (
        !!this.selectedFrequency() &&
        !!this.selectedInstallments() &&
        !!this.investmentAmount() &&
        amount >= MIN_AMOUNT_BTC &&
        !this.amountError()
      );
    }
    return !!this.investmentAmount() && amount >= MIN_AMOUNT_BTC && !this.amountError();
  });

  validateAmount(): void {
    const amount = parseFloat(this.investmentAmount());
    if (this.investmentAmount() && amount < MIN_AMOUNT_BTC) {
      this.amountError.set('Minimum investment is 0.001 BTC');
    } else if (this.investmentAmount() && isNaN(amount)) {
      this.amountError.set('Please enter a valid amount');
    } else {
      this.amountError.set('');
    }
  }

  handleAmountInput(): void {
    this.validateAmount();
    this.clearValidationError();
    const current = parseFloat(this.investmentAmount());
    if (current && this.quickAmounts.includes(current)) {
      this.selectedQuickAmount.set(current);
    } else {
      this.selectedQuickAmount.set(null);
    }
  }

  setQuickAmount(amount: number): void {
    this.investmentAmount.set(amount.toString());
    this.selectedQuickAmount.set(amount);
    this.validateAmount();
    this.clearValidationError();
  }

  selectSubscriptionPattern(pattern: 'pattern1' | 'pattern2'): void {
    this.selectedSubscriptionPattern.set(pattern);
    this.investmentAmount.set(this.satsToBTC(this.calculateSubscriptionPrice(pattern)));
    this.clearValidationError();
  }

  selectInstallments(inst: '3' | '6'): void {
    this.selectedInstallments.set(inst);
    this.clearValidationError();
  }

  selectFrequency(freq: 'weekly' | 'monthly'): void {
    this.selectedFrequency.set(freq);
    this.clearValidationError();
  }

  clearValidationError(): void {
    this.subscriptionPatternError.set('');
    this.frequencyError.set('');
    this.installmentsError.set('');
    this.amountValidationError.set('');
  }

  showValidationErrors(): void {
    this.clearValidationError();
    let firstErrorSelector: string | null = null;
    const type = this.projectTypeNameFromSignal();
    const amount = parseFloat(this.investmentAmount());

    if (type === 'subscription') {
      if (!this.selectedSubscriptionPattern()) {
        this.subscriptionPatternError.set('Please select a subscription plan');
        firstErrorSelector ??= '.subscription-patterns';
      }
      if (!this.investmentAmount() || amount <= 0) {
        this.amountValidationError.set('Please enter a valid subscription amount');
        firstErrorSelector ??= '.form-group input';
      }
    } else if (type === 'fund') {
      if (!this.selectedFrequency()) {
        this.frequencyError.set('Please select a payment frequency');
        firstErrorSelector ??= '.fund-frequency-options';
      }
      if (!this.selectedInstallments()) {
        this.installmentsError.set('Please select the number of installments');
        firstErrorSelector ??= '.fund-installments-options';
      }
      if (!this.investmentAmount() || amount < MIN_AMOUNT_BTC) {
        this.amountValidationError.set('Please enter a funding amount (minimum 0.001 BTC)');
        firstErrorSelector ??= '.form-group input';
      }
    } else {
      if (!this.investmentAmount() || amount < MIN_AMOUNT_BTC) {
        this.amountValidationError.set('Please enter an investment amount (minimum 0.001 BTC)');
        firstErrorSelector ??= '.form-group input';
      }
    }
    if (this.amountError()) {
      this.amountValidationError.set(this.amountError());
      firstErrorSelector ??= '.form-group input';
    }

    if (firstErrorSelector) {
      setTimeout(() => {
        document
          .querySelector(`.invest-page-container ${firstErrorSelector}`)
          ?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      });
    }
  }

  // ---- Flow ----

  generateInvoice(): void {
    if (!this.canSubmit()) {
      this.showValidationErrors();
      return;
    }

    const amountStr = String(this.investmentAmount() || '').trim();
    const amount = parseFloat(amountStr);
    if (isNaN(amount) || !isFinite(amount) || amount <= 0) {
      this.proceedToPayment();
      return;
    }

    // Compare in sats to avoid floating point issues (0.01 BTC threshold)
    const amountInSats = Math.round(amount * 100_000_000);
    if (amountInSats >= APP_THRESHOLD_SATS) {
      this.showAppDownloadModal.set(true);
      return;
    }
    this.proceedToPayment();
  }

  handleMobileInvestClick(): void {
    if (!this.canSubmit()) {
      this.showValidationErrors();
      const card = document.querySelector('.invest-amount-card');
      card?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      return;
    }
    this.generateInvoice();
  }

  proceedToPayment(): void {
    this.showInvestModal.set(true);
    this.paymentStatus.set('awaiting');
    this.selectedNetwork.set('lightning');
  }

  downloadApp(): void {
    this.router.navigate(['/app']);
  }

  /** Alternative: open the invest flow in the Angor web app (external). */
  openExternalApp(): void {
    const host = this.networkService.isMain() ? 'app.angor.io' : 'test.angor.io';
    window.open(`https://${host}/investview/${this.projectId}`, '_blank', 'noopener');
  }

  continueWithWeb(): void {
    this.showAppDownloadModal.set(false);
    this.proceedToPayment();
  }

  closeInvestModal(): void {
    this.showInvestModal.set(false);
    this.paymentStatus.set('awaiting');
    this.selectedNetwork.set('lightning');
  }

  handleNetworkSelect(network: PaymentNetwork): void {
    if (network === 'import') {
      if (this.selectedNetwork() !== 'import') {
        this.previousNetwork = this.selectedNetwork();
      }
      this.selectedNetwork.set('import');
      this.showImportWalletModal.set(true);
      return;
    }
    this.selectedNetwork.set(network);
  }

  handlePayment(): void {
    // Simulated payment (front-end only)
    this.paymentStatus.set('received');
    this.paymentTimeout = setTimeout(() => {
      this.showInvestModal.set(false);
      this.showWalletBackupModal.set(true);
    }, 1500);
  }

  closeImportWalletModal(): void {
    this.showImportWalletModal.set(false);
    this.seedPhraseInput.set('');
    this.seedError.set('');
    this.seedSuccess.set(false);
    if (this.selectedNetwork() === 'import') {
      this.selectedNetwork.set(this.previousNetwork || 'lightning');
    }
  }

  submitSeedImport(): void {
    const cleaned = this.seedPhraseInput().trim().replace(/\s+/g, ' ');
    if (!cleaned) {
      this.seedError.set('Seed phrase is required');
      this.seedSuccess.set(false);
      return;
    }
    this.seedError.set('');
    this.seedSuccess.set(true);
    setTimeout(() => this.closeImportWalletModal(), 1200);
  }

  currentNetworkAddress(): string {
    switch (this.selectedNetwork()) {
      case 'lightning':
        return this.lightningInvoice;
      case 'liquid':
        return this.liquidAddress;
      case 'onchain':
      default:
        return this.investmentAddress;
    }
  }

  currentNetworkLabel(): string {
    switch (this.selectedNetwork()) {
      case 'lightning':
        return 'Lightning Invoice';
      case 'liquid':
        return 'Liquid Address';
      case 'import':
        return 'Import Wallet';
      default:
        return 'Bitcoin Address';
    }
  }

  async copyInvestmentAddress(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.currentNetworkAddress());
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }

  async copyProjectId(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.project()?.projectIdentifier ?? '');
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }

  downloadSeed(): void {
    if (!this.backupPassword() || this.backupPassword().trim() === '') return;

    // Mock seed backup (front-end only)
    const seedPhrase = 'sample seed phrase for investment wallet backup security recovery';
    const blob = new Blob([seedPhrase], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'angor-investment-wallet-seed.txt';
    link.click();
    window.URL.revokeObjectURL(url);

    this.backupPassword.set('');
    this.showBackupPasswordModal.set(false);
    this.seedDownloaded.set(true);
  }

  continueToSuccess(): void {
    this.showWalletBackupModal.set(false);
    this.showSuccessModal.set(true);
  }

  goToInvestments(): void {
    const project = this.project();
    if (!project) return;

    const type = this.projectTypeNameFromSignal();
    const investment: Record<string, unknown> = {
      id: Date.now(),
      projectId: this.projectId,
      projectTitle: this.projectTitle(),
      projectLogo: project.metadata?.picture ?? null,
      amount: parseFloat(this.investmentAmount()),
      investmentDate: new Date().toISOString(),
      status: 'Active',
      stages: this.paymentStages(),
    };

    if (type === 'subscription' && this.selectedSubscriptionPattern()) {
      investment['subscriptionPattern'] = this.selectedSubscriptionPattern();
      investment['totalPayments'] = this.selectedSubscriptionPattern() === 'pattern1' ? 3 : 6;
      investment['paymentsMade'] = 0;
    }
    if (type === 'fund' && this.selectedFrequency() && this.selectedInstallments()) {
      investment['fundFrequency'] = this.selectedFrequency();
      investment['totalPayments'] = parseInt(this.selectedInstallments(), 10) || 3;
      investment['paymentsMade'] = 0;
    }

    try {
      const existing = JSON.parse(localStorage.getItem(HUB_INVESTMENTS_KEY) || '[]');
      existing.unshift(investment);
      localStorage.setItem(HUB_INVESTMENTS_KEY, JSON.stringify(existing));
      localStorage.setItem('angor-new-investment', JSON.stringify(investment));
      window.dispatchEvent(
        new CustomEvent('angor-investments-updated', { detail: { investments: existing } })
      );
    } catch (e) {
      console.warn('Could not persist investments', e);
    }

    this.showSuccessModal.set(false);
    this.seedDownloaded.set(false);
    this.router.navigate(['/project', this.projectId]);
  }

  goBack(): void {
    this.router.navigate(['/project', this.projectId]);
  }

  // ---- Helpers ----

  calculateSubscriptionPrice(pattern: 'pattern1' | 'pattern2'): number {
    const pricePerMonth = this.subscriptionPriceSats();
    const months = pattern === 'pattern1' ? 3 : 6;
    return pricePerMonth * months;
  }

  satsToBTC(sats: number): string {
    return (sats / 100_000_000).toFixed(8);
  }

  btcToSats(btc: string | number): number {
    return Math.round(parseFloat(String(btc)) * 100_000_000);
  }

  formatPaymentDate(dateString: string): string {
    if (!dateString) return 'Not set';
    if (/^\d{1,2}\s+\w+\s+\d{4}$/.test(dateString)) return dateString;
    try {
      const date = new Date(dateString);
      if (isNaN(date.getTime())) return dateString;
      const day = String(date.getDate()).padStart(2, '0');
      const monthAbbr = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      return `${day} ${monthAbbr[date.getMonth()]} ${date.getFullYear()}`;
    } catch {
      return dateString;
    }
  }

  private async generateQr(payload: string, dark: boolean): Promise<void> {
    try {
      const url = await QRCode.toDataURL(payload, {
        width: 256,
        margin: 1,
        color: dark
          ? { dark: '#ffffff', light: '#000000' }
          : { dark: '#000000', light: '#ffffff' },
      });
      this.qrDataUrl.set(url);
    } catch (err) {
      console.error('Failed to generate QR code:', err);
    }
  }
}
